layout_spectrum: 1
name: Chard
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.1881505
  saturation: 0.4477234
  brandColors:
    - '#000000'
    - '#000B1F'
    - '#0D182A'
    - '#33343F'
    - '#415D79'
  lightness: 0.4629005
  rhythmicContrast: 0.8895447
typography_spectrum: 0.2959528
